server:
  port: 8002
  
spring:
  application:
    name: CLIENT-2
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/      
    fetch-registry: false
   
   
feign:
  hystrix:
    enabled: true
