server:
  port: 8003
  
spring:
  application:
    name: CLIENT-3
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/      
    fetch-registry: false
   
feign:
  hystrix:
    enabled: true